### ISSUE TITLE
Issue with mouse picking on PolyData line structure

### ISSUE THREAD

**Issue by tamaynard** [Kitware/react-vtk-js#37]
I'm visualizing a line-based dataset consisting of a sequence of point data. The lines are rendering correctly, however it seems the world space coordinates (worldPosition) returned by the mouse picking feature are incorrect. The value returned appears dependent on the camera position, whereas I would expect the result to be consistent and in line with the input data no matter where the camera is located. I've attached two example files, one an overwritten OBJViewer.js example modified to display lines based on point data contained within example_data.js. To reproduce simply paste these in the usage/Geometry folder and run the build/serve scripts.
[Geometry.zip](https://github.com/Kitware/react-vtk-js/files/7111611/Geometry.zip)

**Comment by tamaynard** [comment]
It appears the Z value is relative to the camera. Is there a function already implemented to convert this to world coordinates, or should I just write one myself?

**Comment by tamaynard** [comment]
Probably related to the HardwareSelector's captureZValues parameter.

**Comment by jourdain** [comment]
[1.2.1](https://github.com/Kitware/react-vtk-js/releases/tag/v1.2.1) should have tacking care of it. Which version are you using?

**Comment by tamaynard** [comment]
I'm using the current release 1.8.2, just double checked to be certain.

**Comment by jourdain** [comment]
Could this be a HiDPI issue with invalid xy input?

**Comment by tamaynard** [comment]
I don't think so, I'm using standard 1080p monitors on both my desktop and laptop, and I can reproduce it on both systems.

**Comment by jourdain** [comment]
Thanks for cross checking those ahead of a deeper investigation. ;-)

**Comment by tamaynard** [comment]
No problem, appreciate any help you can provide as this is the last remaining (known) issue holding up deployment of a prototype of the app I'm developing for a client.

**Comment by floryst** [comment]
Hi @tamaynard, could you provide a minimal repro of the issue using [this codesandbox template](https://codesandbox.io/s/react-vtk-js-base-ddood?file=/src/App.js)? That will help us determine the root cause of your issue.

**Comment by tamaynard** [comment]
[Here](https://codesandbox.io/s/react-vtk-js-base-forked-jog75?file=/src/App.js) you go @floryst. To see the issue, simply click around the vertical line and notice the incorrect Z-value in the debug output on the left-hand side of the screen. Zooming closer to the line using the mousewheel will result in smaller Z-values (which is why I'm thinking it's using the camera's distance from the object as the Z-value).

**Comment by jourdain** [comment]
Just edited the code to have a cube as it is easier to validate since each face should have a fix value along 1 axis.

https://codesandbox.io/s/react-vtk-js-base-forked-0hb5y?file=/src/App.js

**Comment by tamaynard** [comment]
Not quite as prominent, but yes the values don't appear to be correct with the cube either @jourdain. I never noticed until attempting to pick the rendered line as in my example; there the values were completely out of left field so it stuck out like a sore thumb.

**Comment by tamaynard** [comment]
Has there been any movement on this?

**Comment by jourdain** [comment]
I don't think so. @martinken do you see anything strange in that [method](https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js#L597-L604)? 

You can use that [example](https://codesandbox.io/s/react-vtk-js-base-forked-0hb5y?file=/src/App.js) to see that the returned world coordinates are off as we can expect the faces of a cube to have a fix component value.

**Comment by martinken** [comment]
I'll take a look at this right now and see what's going on.

**Comment by martinken** [comment]
That example is behaving like only part of the canvas/renderer window is being shown, or it is scaled or shifted. That is screwing up the picking as the display coordinates being passed in are not matching. For example the lower left corner should have display coordinates of 0,0 but it is reporting 0, 28, that is not correct (see the screenshot below). Likewise if I try to nail down where the center of the window is I'm getting a odd display coordinates which would imply something funny is happening with mouse coordinates mapped to renderer coordinates. When I run a modified HardwareSelector example with a cube everything is fine, so I suspect that the renderer selection code is fine, but the core problem is that mouse event coordinates are not being mapped properly (due to some canvas thing) before being passed into the selection call. @jourdain this is a bit out of my normal codebase, do you want to talk or take over? I'm happy to keep tracking this down but I might need some example between the HardwareSelector example and the code sandbox that I can mess with.

![image](https://user-images.githubusercontent.com/7387719/135866505-d224216d-f048-4afd-bce8-4f4be63763a3.png)

**Comment by martinken** [comment]
@jourdain

**Comment by martinken** [comment]
The coordinate issue is unrelated. The selection issue was due to a bug in the WebGL hardware selection when requesting zbuffer values on translucent actors. In that case there were no zbuffer values so the computed world coordinate was computed incorrectly.

**Comment by jourdain** [comment]
react-vtk-js@1.8.3 should fix that issue
